openapi: "3.0.3"
info:
  title: Transaction API
  version: "1.1.0"
  description: RESTFful API for Nutribox Transaction Model
servers:
  - url: https://localhost:8000
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: object
    TransactionResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
            user_id:
              type: string
            menus:
              type: array
              items:
                type: object
                properties:
                  item_id:
                    type: string
                  quantity:
                    type: integer
            status:
              type: string
            payment_method:
              type: string
            total_price:
              type: number
        errors:
          type: object
  responses:
    BadRequest:
      description: Bad Request - Validation Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              menus:
                - Menus field is empty
              quantity:
                - Menu quantity field is empty
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            message: Unauthenticated.
    NotFound:
      description: Data not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              message:
                - Data not found
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              message:
                - Forbidden
paths:
  /api/users/current/transaction:
    post:
      summary: Create User Transaction
      description: Create new current user transaction
      tags:
        - Current User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - menus
                - payment_method
              properties:
                menus:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      item_id:
                        type: string
                      quantity:
                        type: integer
                        minimum: 1
                payment_method:
                  type: string
                total_price:
                  type: string
      responses:
        "201":
          description: Transaction created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "409":
          description: Data Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                errors:
                  message:
                    - Menu's stock is unavailable
    get:
      summary: Get All User Transaction
      description: Get all current user transaction
      tags:
        - Current User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
      responses:
        "200":
          description: All transaction fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        user_id:
                          type: string
                        menus:
                          type: array
                          items:
                            type: object
                            properties:
                              item_id:
                                type: string
                              quantity:
                                type: integer
                        status:
                          type: string
                        payment_method:
                          type: string
                        total_price:
                          type: number
                  errors:
                    type: object
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /api/users/current/transaction/{id}:
    get:
      summary: Get User Transaction
      description: Get current user transaction by id
      tags:
        - Current User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
        - name: id
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: Transaction fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
    patch:
      summary: Edit User Transaction Status by id
      description: Edit current user transaction status by id
      tags:
        - Current User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
        - name: id
          in: path
          schema:
            type: number
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        "200":
          description: Transaction status edited successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      summary: Delete Transaction
      description: Delete transaction by id
      tags:
        - Current User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
        - name: id
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: Transaction deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                  errors:
                    type: object
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /api/transaction:
    get:
      summary: Get All Transactions
      description: Get all transactions (admin only)
      tags:
        - Admin
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
        - name: user_id
          in: query
          schema:
            type: number
          required: false
        - name: min_price
          in: query
          schema:
            type: number
          required: false
        - name: max_price
          in: query
          schema:
            type: number
          required: false
        - name: include_deleted
          in: query
          schema:
            type: boolean
          required: false
        - name: status
          in: query
          schema:
            type: string
          required: false
        - name: payment_method
          in: query
          schema:
            type: string
          required: false
      responses:
        "200":
          description: All transaction fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        user_id:
                          type: string
                        menus:
                          type: array
                          items:
                            type: object
                            properties:
                              item_id:
                                type: string
                              quantity:
                                type: integer
                        status:
                          type: string
                        payment_method:
                          type: string
                        total_price:
                          type: number
                  errors:
                    type: object
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
  /api/transaction/{id}:
    get:
      summary: Get Transaction
      description: Get transaction by id
      tags:
        - Admin
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
        - name: id
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: Transaction fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
    patch:
      summary: Edit Transaction Status by id
      description: Edit transaction status by id (admin only)
      tags:
        - Admin
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
        - name: id
          in: path
          schema:
            type: number
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        "200":
          description: Transaction status edited successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      summary: Delete transaction by id
      description: Delete transaction by id (admin only)
      tags:
        - Admin
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer <token>
          required: true
        - name: id
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: Transaction deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                  errors:
                    type: object
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
